<a href="https://colab.research.google.com/github/yashkardile7743/DataScience-25-A/blob/main/prac1OS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
# Create a 3x3 square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original 3x3 matrix:")
print(matrix)
 #Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0
